### ISSUE TITLE
津波などその他の天災にも対応出来るように

### ISSUE THREAD

**Issue by fuyutsuki** [HADAlove0202/EEW-Plugin-for-PocketMineMP#2]
[経緯はこちらを参照](https://web.lobi.co/group/a5babead5099b687d25354a8c94ca81309b290e3/chat/591664396166639616)

**Comment by HADAlove0202** [comment]
そのAPIの補足事項に
リクエスト数が過大とならないように、IPアドレス単位で30リクエスト/分以内にとあるので配布しちゃうと複数IPから多くのリクエストが行くことになってしまい厳しいと思います。
出来るなら中間にサーバーを作り分散させたいのですがサーバーを持っていないし許可が出るかがわかりません。

**Comment by fuyutsuki** [comment]
お返事ありがとうございます
